/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AFourPaper: typeof import('./src/components/AFourPaper/AFourPaper.vue')['default']
    CardContainer: typeof import('./src/components/CardContainer/CardContainer.vue')['default']
    DivContainer: typeof import('./src/components/DivContainer.vue')['default']
    ICarbonCloudUpload: typeof import('~icons/carbon/cloud-upload')['default']
    ICarbonDocumentPreliminary: typeof import('~icons/carbon/document-preliminary')['default']
    ICarbonLanguage: typeof import('~icons/carbon/language')['default']
    ICarbonUserAvatarFilled: typeof import('~icons/carbon/user-avatar-filled')['default']
    IframeContainer: typeof import('./src/components/IframeContainer.vue')['default']
    MicroContainer: typeof import('./src/components/MicroContainer.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NavTabs: typeof import('./src/components/NavTabs/NavTabs.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NPopover: typeof import('naive-ui')['NPopover']
    NProgress: typeof import('naive-ui')['NProgress']
    NResult: typeof import('naive-ui')['NResult']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTab: typeof import('naive-ui')['NTab']
    NTabs: typeof import('naive-ui')['NTabs']
    NText: typeof import('naive-ui')['NText']
    PageContainer: typeof import('./src/components/PageContainer.vue')['default']
    PageWrapper: typeof import('./src/components/PageWrapper.vue')['default']
    QueryButtons: typeof import('./src/components/QueryButtons.vue')['default']
    RouterButton: typeof import('./src/components/RouterButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    S3Uploader: typeof import('./src/components/S3Uploader/S3Uploader.vue')['default']
    StatusCard: typeof import('./src/components/StatusCard/StatusCard.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
    TwinDatePicker: typeof import('./src/components/TwinDatePicker.vue')['default']
    UploaderPop: typeof import('./src/components/UploaderPop.vue')['default']
    UploadProgress: typeof import('./src/components/UploadProgress.vue')['default']
    UserProfileMenu: typeof import('./src/components/UserProfileMenu.vue')['default']
  }
}
